version: '3'

services:
  influxDB:
# below image contains data copied from an existing InfluxDB database (localdata)
    image: influxdb-carlo
    container_name: influxDB
    restart: always
    ports:
      - 8086:8086
#    volumes:
#      - influxdb:/var/lib/influxdb

  grafana:
# below image contains a dashboard (json file) copied from the Raspberry Pi
    image: grafana-carlo-7.5.2
    container_name: grafana
    restart: always
    ports:
    - 3000:3000
#    volumes:
#    - grafana:/var/lib/grafana

  weather:
      container_name: "weather"
      build: .
      depends_on:
        - "grafana"
        - "influxDB"
      stdin_open: true
      tty: true


#volumes:
#   influxdb:
#     external: true

