{
 "title": "Home automation logging RP",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "city",
    "query": "show tag values on \"localdata\" with key=\"location\""
   }
  ]
 },
 "panels": [
  { "title": "Solar Panels", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Solar Panel Production",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_location",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "solarpanel",
     "select": [
      [
       { "params": [ "power total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Today's Production",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_location",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "solarpanel",
     "select": [
      [
       { "params": [ "power today" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current Power",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_location",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "solarpanel",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Solar Panel Temperature",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_location",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "solarpanel",
     "select": [
      [
       { "params": [ "Temp" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Solar Panel Power (daily total)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "alias": "$tag_location",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "location" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "solarpanel",
     "query": "select sum(\"max\") from (SELECT max(\"power today\") FROM \"solarpanel\" WHERE $timeFilter GROUP BY time(1d), \"location\" fill(null)) group by time(1d)",
     "select": [
      [
       { "params": [ "power today" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Solar Panel Power",
   "type": "graph",
   "gridPos": { "h": 10, "w": 13, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "$tag_location",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "location" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "solarpanel",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Solar Panel Power (1hr average)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "$tag_location",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "location" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "solarpanel",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Home Lights",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Home Lights",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_light",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "light" ], "type": "tag" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "hue_lights",
       "select": [
        [
         { "params": [ "on" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Home Lights",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_light",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "light" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "hue_lights",
       "select": [
        [
         { "params": [ "on" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Weather data",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "City Temperature",
     "type": "graph",
     "gridPos": { "h": 11, "w": 11, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "yaxes": [
      { "format": "celsius" }
     ],
     "targets": [
      {
       "alias": "$tag_location",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "location" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "temperature",
       "select": [
        [
         { "params": [ "temperature" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "location", "operator": "=~", "value": "/^$city$/" }
       ]
      }
     ]
    },
    {
     "title": "Wind Speed",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 11, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "velocityms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_location",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "location" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "wind",
       "query": "SELECT mean(\"speed\") FROM \"wind\" WHERE (\"location\" =~ /^$city$/) AND $timeFilter GROUP BY time($__interval), \"location\" fill(null)",
       "select": [
        [
         { "params": [ "speed" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "location", "operator": "=~", "value": "/^$city$/" }
       ]
      }
     ]
    },
    {
     "title": "Wind Direction",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 14, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "degree" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_location",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "location" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "wind",
       "select": [
        [
         { "params": [ "direction" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "location", "operator": "=~", "value": "/^$city$/" }
       ]
      }
     ]
    },
    {
     "title": "Humidity",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 17, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_location",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "location" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "humidity",
       "select": [
        [
         { "params": [ "humidity" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "location", "operator": "=~", "value": "/^$city$/" }
       ]
      }
     ]
    },
    {
     "title": "Pressure",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 19, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_location",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "location" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pressure",
       "select": [
        [
         { "params": [ "pressure" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "location", "operator": "=~", "value": "/^$city$/" }
       ]
      }
     ]
    },
    {
     "title": "Weather",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 22, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_location",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "location" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "weather_type",
       "select": [
        [
         { "params": [ "weather_type" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "location", "operator": "=~", "value": "/^$city$/" }
       ]
      }
     ]
    },
    {
     "title": "Home Temperature",
     "type": "graph",
     "gridPos": { "h": 8, "w": 13, "x": 11, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "yaxes": [
      { "format": "celsius" }
     ],
     "targets": [
      {
       "alias": "$tag_sensor",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "sensor" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "hue_temperature",
       "select": [
        [
         { "params": [ "temperature" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Wind Speed",
     "type": "graph",
     "gridPos": { "h": 11, "w": 11, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "velocityms" } },
     "yaxes": [
      { "format": "velocityms" }
     ],
     "targets": [
      {
       "alias": "$tag_location",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "location" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "wind",
       "select": [
        [
         { "params": [ "speed" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "location", "operator": "=~", "value": "/^$city$/" }
       ]
      }
     ]
    }
   ]
  }
 ]
}