FROM grafana/grafana:7.5.2
# (v7.5.2 run now on the RP)
# (v8.1.2 is the latest version)

# docker run -d --name=grafana -p 3000:3000 grafana/grafana:7.5.2
# copy existing grafana data into this container using the json dashboard data
# docker commit [grafana] [grafana-carlo:7.5.2]